### ISSUE TITLE
Create Wiki Page for Enocraft Cosmetic Changes

### ISSUE THREAD

**Issue by forgeno** [EnocraftMC/UltraCosmetics#3]
### What is the goal of this ticket?
To provide developers who come back to /ucs commands, insight on how the commands are formatted and their functionality

### Why is this a priority?
In order for other developers to work together without too much disturbance from the same questions being asked. A shared knowledge portal should be created to store this information.

### Acceptance criteria:
- [x] wiki documentation on commands and features for #1 
- [x] wiki documentation on commands and features for #2 
- [x]  wiki documentation on commands and features for #4 
### Any additional information that you would
